### ISSUE TITLE
Dutch Geo data improvements

### ISSUE THREAD

**Issue by smartey** [eruci/geocode#3]
Hi there,

I like the way geocode.xyz enable others to make use of their API getting geo data and I would like to help you fix some data error. This concerns the data for The Netherlands.

Here is what is being returned in detail using: https://geocode.xyz/53.00706,6.07067?geoit=xml

`<geodata>
<latt>53.00707</latt>
<longt>6.07069</longt>
<elevation>1</elevation>
<timezone>Europe/Amsterdam</timezone>
<city>Gorredijk</city>
<prov>NL</prov>
<region>Gemeente Opsterland, Friesland</region>
<state>NL</state>
<statename/>
<country>Netherlands</country>`

This is part of the returned data and needs some fixes, everything else is correct.
What should be fixed are the following fields:

`<prov>` returns always NL but should return the province, in the above sample that should be 'Friesland'
`<region>` returns two seperate field data in one, 'state' and 'region', in above sample region should be 'Noord Nederland' however this data is missing. (can be freely updated if you want to)
`<state>` returns always NL but should return the state/county, in the above sample that should be 'Gemeente Opsterland'

Hope you're willing/able to make these improvements.
Let me know if you need help with the data.

Regards,
Eric

**Comment by eruci** [comment]
These are fair observations - however changing the parameter values now would break a lot of existing codebases that rely on this api. For eg, people have been using the api by parsing the 'region' parameter and retrieving from in the state/region. Also, many expect the 'prov' to return the country code. Hence these changes can not be made at this time.
